### ISSUE TITLE
Gmail would not let me send a dll file, so i'm just gonna create a issue here and send it.

### ISSUE THREAD

**Issue by Nukley** [silverf0x/RpcView#10]
https://github.com/Nukley/Nukley.github.io/blob/master/rpcrt4.dll

**Comment by Nukley** [comment]
https://github.com/Nukley/Nukley.github.io/blob/f/rpcrt4.dll
Here is the system32 one

**Comment by silverf0x** [comment]
fixed in commit daf87dcc993c95fd2abc696ad43e6b2ee86c140a
