### ISSUE TITLE
Hang with VBS enabled due to EnumProcessModulesEx ignored return value

### ISSUE THREAD

**Issue by masthoon** [silverf0x/RpcView#35]
**RpcView** hangs when it tries to read _LsaIso_ process because the return value of _EnumProcessModulesEx_ is not checked (it fails on trustlet and sets last error to _ERROR_NOACCESS_) moreover cbSize is not initialized to 0 (may be large -> hang during loop).
https://github.com/silverf0x/RpcView/blob/7302b614ceae09721c415e87d8752d7d2214f3ac/RpcCore/RpcCore.c#L210-L227

Tested Fix:
```c
L226	if(!EnumProcessModulesEx(hProcess, NULL, 0, &cbSize, LIST_MODULES_ALL))
L227		goto End;
```

**Comment by silverf0x** [comment]
Thanks for the fix.
