### ISSUE TITLE
unsupported runtime version for rpcrt4.dll in Win10

### ISSUE THREAD

**Issue by mmcer** [silverf0x/RpcView#38]
OS version: Win10 18363.657 (1909)

this unsupported message pop up, and this reop not updated for 3 years, does anyone can help to check it? 

thanks.

**Comment by gattacker** [comment]
Hi! Same problem with Windows 1903 (18362.657)

**Comment by pwna5aurus** [comment]
Same.  10.0.18363 N/A Build 18363

**Comment by parsiya** [comment]
Using the builds from the release section resulted in the same error above.

Follow the link in the readme `You can download the last automatically built release` which goes to https://ci.appveyor.com/project/silverf0x/rpcview/build/artifacts. I downloaded the binaries there and did not have an issue.

**Comment by pwna5aurus** [comment]
@parsiya Worked great.  Thank you much!

**Comment by mmcer** [comment]
@parsiya it works, thanks a lot.

**Comment by anupgithub** [comment]
I am still seeing this issue. How can I figure out which runtime version I need and where can I find out. I used the released build from the following link which was mentioned above.
https://ci.appveyor.com/project/silverf0x/rpcview/build/artifacts

**Comment by anesh** [comment]
> 
> 
> I am still seeing this issue. How can I figure out which runtime version I need and where can I find out. I used the released build from the following link which was mentioned above.
> https://ci.appveyor.com/project/silverf0x/rpcview/build/artifacts

Go to C:\Windows\System32 and right click on rpcrt4.dll and in the details check for file version, that would be your runtime

**Comment by phackt** [comment]
Any news about this ?

**Comment by lihas** [comment]
Seeing this issue with the latest release of rpcview. Windows 10 19044

**Comment by lihas** [comment]
Fix: https://itm4n.github.io/fuzzing-windows-rpc-rpcview/

**Comment by maxway2021** [comment]
Hey guys, I just wrote a script to patch and build RpcView for you, check it out!
https://github.com/maxway2021/rpcview_builder
