### ISSUE TITLE
RpcView on Windows 10.0.19041.546 does not show any process

### ISSUE THREAD

**Issue by anesh** [silverf0x/RpcView#43]
i did a build of RpcView on Windows 10.0.19041.546, but i do not see any process, also when i click on File "Show Detail of All Processes is grayed out"

**Comment by silverf0x** [comment]
I just updated the project.
Could you test the last binaries please? I cannot reproduce the problem.

**Comment by anesh** [comment]
> 
> 
> I just updated the project.
> Could you test the last binaries please? I cannot reproduce the problem.

Thanks a lot!, The new binary works now!
