### ISSUE TITLE
Artifacts missing on AppVeyor

### ISSUE THREAD

**Issue by sploutchy** [silverf0x/RpcView#56]
Howdy RpcView team,

I wanted to download the automatic build of RpcView but the artifacts seem to expire and disappear after some time:
https://ci.appveyor.com/project/silverf0x/rpcview/build/artifacts

Can you recompile the latest version and/or make them not expire?

Merci beaucoup!

**Comment by cwiph** [comment]
hi, unfortunately the artifacts have been deleted again. Would it be possible to provide new releases?
