### ISSUE TITLE
RpcView à ce genre de look old school

### ISSUE THREAD

**Issue by 1orenz0** [silverf0x/RpcView#7]
Mamène qu'est-ce qui s'est passé ? J'ai téléchargé `RpcView` tel qu'il est packagé par Appveyor, et je téma ce genre de look au lancement : 

![image](https://user-images.githubusercontent.com/35742146/36786997-c75fc08e-1c88-11e8-919b-afe8ee766cb2.png)

T'es nostalgique des années `NT 4.0`, c'est ça ? On est en 2018, il faut que ça blingue si tu veux espérer refourguer ta came.

Allez je te chambre, c'est en réalité de la faute des srabs de chez Qt : [default widget style is not flat anymore](https://bugreports.qt.io/browse/QTCREATORBUG-19150?gerritReviewStatus=All). Depuis `Qt 5.10` il faut également packager le dossier `styles` (comme pour le dossier `platform`) pour obtenir les styles spécifiques windows.

Tkt le poto Lolo a charbonné et t'as trouvé la solution : `winqtdeploy` est un exe qui s'occupe de déployer les dépendances Qt automatiquement, comme ça t'as plus a t'occuper de savoir quelles dlls à copier : 

```
cd C:\projects\RpcView
mkdir Build\x64
cd C:\projects\RpcView\Build\x64
set CMAKE_PREFIX_PATH=C:\Qt\5.10.0\msvc2015_64
cmake ..\.. -G"Visual Studio 14 2015 Win64" -T"v140_xp"
cmake --build . --config release
cd C:\projects\RpcView\Build\x64\bin\Release
mkdir RpcView64
copy *.dll RpcView64\
copy *.exe RpcView64\
C:\Qt\5.10.0\msvc2015_64\bin\windeployqt.exe --release RpcView64\
7z a RpcView64.7z RpcView64
cd C:\projects\RpcView
mkdir Build\x86
cd C:\projects\RpcView\Build\x86
set CMAKE_PREFIX_PATH=C:\Qt\5.10.0\msvc2015
cmake ..\.. -G"Visual Studio 14 2015" -T"v140_xp"
cmake --build . --config release
cd C:\projects\RpcView\Build\x86\bin\Release
mkdir RpcView32
copy *.exe RpcView32\
copy *.dll RpcView32\
C:\Qt\5.10.0\msvc2015\bin\windeployqt.exe --release RpcView32\
7z a RpcView32.7z RpcView32
```

ça a quand même plus de gueule avec le style correct : 

![image](https://user-images.githubusercontent.com/35742146/36787704-52b523f2-1c8b-11e8-94db-7bcd14875de7.png)

Tu peux tester mes artifacts ici : https://ci.appveyor.com/project/1orenz0/rpcview/build/1.0.23

QDS,

L'Empereur du Sale.

**Comment by silverf0x** [comment]
ok, merci
